apiVersion: v1
kind: Namespace
metadata:
  name: testing
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: batch/v1
kind: Job
metadata:
  name: proxy-shutdown
  namespace: testing
  annotations:
    something: enabled
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: wait-and-shutdown
          image: linkerd-await-test:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ANNOTATION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['linkerd.io/enabled']
      restartPolicy: Never
